spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: changgou_goods_route
          uri: lb://goods
          predicates:
            - Path=/api/album/**,/api/brand/**,/api/cache/**,/api/categoryBrand/**,/api/category/**,/api/para/**,/api/pref/**,/api/sku/**,/api/spec/**,/api/spu/**,/api/stockBack/**,/api/template/**
          filters:
            #- PrefixPath=/brand
            - StripPrefix=1
          #用户微服务
        - id: changgou_user_route
          uri: lb://user
          predicates:
            - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**,/api/validateCode/**
          filters:
            - StripPrefix=1
          #认证微服务
        - id: changgou_oauth_user
          uri: lb://user-auth
          predicates:
            - Path=/api/oauth/**
          filters:
            - StripPrefix=1
   #搜索微服务
        - id: changgou_service_search
          uri: lb://search
          predicates:
            - Path=/api/search/**
          filters:
            - StripPrefix=1
#搜索微服务
        - id: changgou_web_user
          uri: lb://user-web
          predicates:
            - Path=/api/wuser/**
          filters:
            - StripPrefix=1
        #订单微服务
        - id: changgou_order_route
          uri: lb://order
          predicates:
            - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
          filters:
            - StripPrefix=1
        #购物车订单渲染微服务
        - id: changgou_order_web_route
          uri: lb://order-web
          predicates:
            - Path=/api/wcart/**,/api/worder/**,/api/wxpay/**,/api/alipay/**
          filters:
            - StripPrefix=1
      #秒杀微服务
        - id: changgou_seckill_route
          uri: lb://seckill
          predicates:
            - Path=/api/seckillgoods/**,/api/seckillorder/**
          filters:
            - StripPrefix=1
      #秒杀渲染微服务
        - id: changgou_seckill_web_route
          uri: lb://seckill-web
          predicates:
            - Path=/api/wseckillgoods/**,/api/wseckillorder/**
          filters:
            - StripPrefix=1
      #评论服务
        - id: changgou_comment
          uri: lb://comment
          predicates:
            - Path=/api/comment/**
          filters:
            - StripPrefix=1

     #评论服务界面（商品详情服务）
        - id: changgou_comment_web
          uri: lb://goods-web
          predicates:
            - Path=/api/wcomment/**
          filters:
            - StripPrefix=1

      #快递地图服务
        - id: changgou_kuaidi
          uri: lb://kuaidi
          predicates:
            - Path=/api/kuaidi/**
          filters:
            - StripPrefix=1

        #用户渲染微服务
        - id: changgou_user_web_route
          uri: lb://webuser
          predicates:
            - Path=/api/webuser/**
          filters:
            - StripPrefix=1
        #file文件服务
        - id: changgou_file
          uri: lb://file
          predicates:
            - Path=/api/file/**
          filters:
            - StripPrefix=1

  redis:
    host: 192.168.200.128
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
    ip-address: localhost
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true